### ISSUE TITLE
TODO - Christmas Break 2022

### ISSUE THREAD

**Issue by ravenofliberty** [ravenofliberty/rates#21]
**Immediate goals**
- [ ] Fix the yield curve construction and interpolation to use splines by default
- [ ] Ensure that default methods used for discount factors are consistent with mkt. conversions
- [ ] Cross-check pricing results with model doc

**Medium-term goal**
- [ ] Cover and implement chapter I and II from the book
- [ ] Get comfortable with the math of pricing and numeraire change

**Long-term goal**
- [ ] implement all instruments from the Brigo-Mercurio book, together with pricing
- [ ] set up first rates OTC strategy (including infra, ability to close the position in a clean way etc.)
